// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML_NET_TutorialML.Model
{
    public class ModelInput
    {
        [ColumnName("Sentiment"), LoadColumn(0)]
        public string Sentiment { get; set; }


        [ColumnName("SentimentText"), LoadColumn(1)]
        public string SentimentText { get; set; }


    }
}
